#' Merging all available Data-Files with more than 0 rows (with same and different column sizes)
#'
#' You have to filter the list of data-tibbles to merge a subset of the files
#'
#' @param data List of Data-Files in Data-Directory generated by getTibbleOfDataDirectoryOfProject
#'
#' @return Merged Data-Files as a long tibble
#' @export
#' @import dplyr
#'
#' @examples mergedData <- mergeDataTibble(getTibbleOfDataDirectoryOfProject("#######",12345))
mergeDataTibble <- function(data) {
  if(!dplyr::is.tbl(data)) {return(tibble())}
  dataMerged <- data %>%
    filter(fileDimRows > 0) %>%
    select(file_contents) %>%
    tidyr::unnest(cols = c(file_contents)) %>%
    replace(. == "", NA)
  return(dataMerged)
}

